spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/user/**
              filters:
                - StripPrefix=2

            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/api/order/**
              filters:
                - StripPrefix=2

            - id: auth-service-route
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

